-- Run this once in Supabase SQL Editor after the original schema.sql.
alter table public.companies add column if not exists created_by_email text;
alter table public.contacts add column if not exists created_by_email text;
alter table public.trades add column if not exists created_by_email text;
alter table public.companies alter column created_by set default auth.uid();
alter table public.contacts alter column created_by set default auth.uid();
alter table public.trades alter column created_by set default auth.uid();
alter table public.companies alter column created_by_email set default (auth.jwt() ->> 'email');
alter table public.contacts alter column created_by_email set default (auth.jwt() ->> 'email');
alter table public.trades alter column created_by_email set default (auth.jwt() ->> 'email');
drop policy if exists "users view companies" on public.companies;
drop policy if exists "users add companies" on public.companies;
drop policy if exists "users update companies" on public.companies;
drop policy if exists "users view trades" on public.trades;
drop policy if exists "users add trades" on public.trades;
drop policy if exists "users view company trades" on public.company_trades;
drop policy if exists "users add company trades" on public.company_trades;
drop policy if exists "users view contacts" on public.contacts;
drop policy if exists "users add contacts" on public.contacts;
drop policy if exists "employees view companies" on public.companies;
drop policy if exists "employees add companies" on public.companies;
drop policy if exists "employees update companies" on public.companies;
drop policy if exists "employees view trades" on public.trades;
drop policy if exists "employees add trades" on public.trades;
drop policy if exists "employees view company trades" on public.company_trades;
drop policy if exists "employees add company trades" on public.company_trades;
drop policy if exists "employees view contacts" on public.contacts;
drop policy if exists "employees add contacts" on public.contacts;
create policy "employees view companies" on public.companies for select to authenticated using(true);
create policy "employees add companies" on public.companies for insert to authenticated with check(created_by=auth.uid());
create policy "employees update companies" on public.companies for update to authenticated using(true) with check(true);
create policy "employees view trades" on public.trades for select to authenticated using(true);
create policy "employees add trades" on public.trades for insert to authenticated with check(created_by=auth.uid());
create policy "employees view company trades" on public.company_trades for select to authenticated using(true);
create policy "employees add company trades" on public.company_trades for insert to authenticated with check(true);
create policy "employees view contacts" on public.contacts for select to authenticated using(true);
create policy "employees add contacts" on public.contacts for insert to authenticated with check(created_by=auth.uid());
drop policy if exists "employees delete companies" on public.companies;
drop policy if exists "employees update contacts" on public.contacts;
drop policy if exists "employees delete contacts" on public.contacts;
drop policy if exists "employees delete company trades" on public.company_trades;
create policy "employees delete companies" on public.companies for delete to authenticated using(true);
create policy "employees update contacts" on public.contacts for update to authenticated using(true) with check(true);
create policy "employees delete contacts" on public.contacts for delete to authenticated using(true);
create policy "employees delete company trades" on public.company_trades for delete to authenticated using(true);
