'use client'
import { useEffect,useMemo,useState } from 'react'
import { supabase } from '@/lib/supabase'
import { Building2,Search,Plus,Phone,Mail,MapPin,Users,X,ChevronRight,HardHat,Droplets,Truck,Construction } from 'lucide-react'

type Trade={id:string;name:string;color:string}
type Contact={id:string;name:string;job_title:string|null;phone:string|null;email:string|null}
type Company={id:string;name:string;city:string|null;state:string|null;website:string|null;notes:string|null;status:string;company_trades:{trades:Trade}[];contacts:Contact[]}
const icons=[Droplets,Construction,Truck,HardHat]

export default function Home(){
 const [companies,setCompanies]=useState<Company[]>([]),[trades,setTrades]=useState<Trade[]>([]),[query,setQuery]=useState(''),[trade,setTrade]=useState('all'),[loading,setLoading]=useState(true),[modal,setModal]=useState<'company'|'contact'|'trade'|null>(null),[selected,setSelected]=useState<Company|null>(null),[notice,setNotice]=useState('')
 async function load(){setLoading(true);const [{data:c},{data:t}]=await Promise.all([supabase.from('companies').select('*, contacts(*), company_trades(trades(*))').order('name'),supabase.from('trades').select('*').order('name')]);setCompanies((c as Company[])||[]);setTrades(t||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const shown=useMemo(()=>companies.filter(c=>{const hay=[c.name,c.city,c.state,...c.contacts.flatMap(x=>[x.name,x.email,x.phone]),...c.company_trades.map(x=>x.trades.name)].join(' ').toLowerCase();return hay.includes(query.toLowerCase())&&(trade==='all'||c.company_trades.some(x=>x.trades.id===trade))}),[companies,query,trade])
 function openContact(c:Company){setSelected(c);setModal('contact')}
 return <main>
  <header><div className="brand"><div className="logo">LGC</div><div><b>LGC GLOBAL</b><span>Contractor Directory</span></div></div><button className="primary" onClick={()=>setModal('company')}><Plus size={18}/> Add Company</button></header>
  <section className="hero"><div><p className="eyebrow">FIELD RESOURCE NETWORK</p><h1>Find the right contractor.<br/><em>Right when you need them.</em></h1><p>One reliable directory for LGC Global’s subcontractors, trades, and contacts.</p></div><div className="stats"><b>{companies.length}</b><span>Companies</span><b>{trades.length}</b><span>Trades</span><b>{companies.reduce((n,c)=>n+c.contacts.length,0)}</b><span>Contacts</span></div></section>
  <section className="content">
   {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
   <div className="toolbar"><div className="search"><Search/><input placeholder="Search company, contact, phone, email, city or trade…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={trade} onChange={e=>setTrade(e.target.value)}><option value="all">All trades</option>{trades.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>
   <div className="sectionTitle"><div><span>Browse by trade</span><h2>Specialty contractors</h2></div><button className="textButton" onClick={()=>setModal('trade')}><Plus size={16}/> Add trade</button></div>
   <div className="tradeGrid"><button className={trade==='all'?'trade active':'trade'} onClick={()=>setTrade('all')}><Building2/><b>All Companies</b><span>{companies.length} contractors</span></button>{trades.slice(0,7).map((t,i)=>{const I=icons[i%icons.length];const count=companies.filter(c=>c.company_trades.some(x=>x.trades.id===t.id)).length;return <button key={t.id} className={trade===t.id?'trade active':'trade'} onClick={()=>setTrade(t.id)}><I/><b>{t.name}</b><span>{count} contractors</span></button>})}</div>
   <div className="sectionTitle"><div><span>Directory</span><h2>{trade==='all'?'All companies':trades.find(t=>t.id===trade)?.name}</h2></div><small>{shown.length} result{shown.length===1?'':'s'}</small></div>
   {loading?<div className="empty">Loading directory…</div>:shown.length===0?<div className="empty"><Search/><h3>No contractors found</h3><p>Try another search or add a new company.</p></div>:<div className="companyGrid">{shown.map(c=><article key={c.id} className="company"><div className="companyTop"><div className="avatar">{c.name.slice(0,2).toUpperCase()}</div><div><h3>{c.name}</h3><p><MapPin size={14}/>{[c.city,c.state].filter(Boolean).join(', ')||'Location not added'}</p></div><span className="status">{c.status}</span></div><div className="tags">{c.company_trades.map(x=><span key={x.trades.id}>{x.trades.name}</span>)}</div><div className="contacts">{c.contacts.slice(0,2).map(x=><div key={x.id}><div><b>{x.name}</b><small>{x.job_title||'Contact'}</small></div><div className="actions">{x.phone&&<a href={'tel:'+x.phone}><Phone/></a>}{x.email&&<a href={'mailto:'+x.email}><Mail/></a>}</div></div>)}{!c.contacts.length&&<p>No contacts yet</p>}</div><button className="addContact" onClick={()=>openContact(c)}><Plus size={16}/> Add new contact <ChevronRight size={16}/></button></article>)}</div>}
  </section>
  {modal&&<Modal title={modal==='company'?'Add company':modal==='contact'?`Add contact to ${selected?.name}`:'Add trade'} close={()=>setModal(null)}><Form kind={modal} company={selected} trades={trades} companies={companies} done={m=>{setModal(null);setNotice(m);load()}} openExisting={c=>{setSelected(c);setModal('contact')}}/></Modal>}
 </main>
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><div><span>LGC GLOBAL</span><h2>{title}</h2></div><button onClick={close}><X/></button></div>{children}</div></div>}

function Form({kind,company,trades,companies,done,openExisting}:{kind:string;company:Company|null;trades:Trade[];companies:Company[];done:(m:string)=>void;openExisting:(c:Company)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[name,setName]=useState('')
 const norm=(s:string)=>s.toLowerCase().replace(/\b(incorporated|corporation|company|limited|inc|corp|co|llc|ltd)\b/g,'').replace(/[^a-z0-9]/g,'')
 const duplicate=kind==='company'&&name.length>2?companies.find(c=>norm(c.name)===norm(name)):undefined
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget)
  try{
   if(kind==='company'){if(duplicate){openExisting(duplicate);return}const {data:c,error}=await supabase.from('companies').insert({name,city:f.get('city'),state:f.get('state')||'MI',website:f.get('website'),notes:f.get('notes')}).select().single();if(error)throw error;const ids=f.getAll('trades');if(ids.length)await supabase.from('company_trades').insert(ids.map(trade_id=>({company_id:c.id,trade_id})));const cn=String(f.get('contact_name')||'').trim();if(cn)await supabase.from('contacts').insert({company_id:c.id,name:cn,job_title:f.get('job_title'),phone:f.get('phone'),email:f.get('email')});done(`${name} was added successfully.`)}
   if(kind==='contact'){const email=String(f.get('email')||'').trim()||null,phone=String(f.get('phone')||'').trim()||null;const exists=company?.contacts.some(c=>(email&&c.email?.toLowerCase()===email.toLowerCase())||(phone&&c.phone?.replace(/\D/g,'')===phone.replace(/\D/g,'')));if(exists)throw new Error('This email or phone number already exists for this company.');const {error}=await supabase.from('contacts').insert({company_id:company?.id,name:f.get('contact_name'),job_title:f.get('job_title'),phone,email});if(error)throw error;done(`New contact added to ${company?.name}.`)}
   if(kind==='trade'){const {error}=await supabase.from('trades').insert({name});if(error)throw error;done(`${name} trade was added.`)}
  }catch(x:any){setError(x.message||'Unable to save. Please try again.')}finally{setBusy(false)}}
 return <form onSubmit={submit}>{error&&<div className="formError">{error}</div>}{kind==='company'&&<><label>Company name *<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g., Metro Piping"/></label>{duplicate&&<div className="duplicate"><b>{duplicate.name} already exists.</b><span>Duplicate companies cannot be added.</span><button type="button" onClick={()=>openExisting(duplicate)}>Add a new contact instead</button></div>}<div className="two"><label>City<input name="city" placeholder="Detroit"/></label><label>State<input name="state" defaultValue="MI"/></label></div><label>Website<input name="website" placeholder="https://"/></label><fieldset><legend>Trades *</legend><div className="checks">{trades.map(t=><label key={t.id}><input type="checkbox" name="trades" value={t.id}/>{t.name}</label>)}</div></fieldset><h3 className="subhead">Primary contact (optional)</h3></>}{kind==='trade'&&<label>Trade name *<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g., Traffic Control"/></label>}{kind!=='trade'&&<><label>Contact name {kind==='contact'&&'*'}<input required={kind==='contact'} name="contact_name" placeholder="Full name"/></label><div className="two"><label>Job title<input name="job_title" placeholder="Project Manager"/></label><label>Phone<input name="phone" type="tel" placeholder="(248) 555-0100"/></label></div><label>Email<input name="email" type="email" placeholder="name@company.com"/></label>{kind==='company'&&<label>Notes<textarea name="notes" placeholder="Capabilities, service area, or other notes"/></label>}</>}<button className="submit" disabled={busy||!!duplicate}>{busy?'Saving…':kind==='contact'?'Add contact':kind==='trade'?'Add trade':'Add company'}</button></form>
}
